name: Testing

on:
  workflow_dispatch:
    branches:
      - master
      - develop
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
    - master
    - develop

defaults:
  run:
    shell: bash -l {0}

jobs:
  pytest:
    name: Pytests on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
        # if we ever need to enable this for Windows too, just replace with this line:
        # os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: ci-env
        environment-file: environment.yml
        create-args: >-
          python=${{ matrix.python-version }}
        init-shell: bash
        
    - name: Install dependencies
      run: pip install -e .
    - run: git lfs pull
    - name: Test with pytest
      run: pytest pastis
